### ISSUE TITLE
How to use another MySql after wellcommerce has been deployed to heroku?

### ISSUE THREAD

**Issue by educate** [WellCommerce/WellCommerce#107]
Hi,
I've deployed wellcommerce sample site to heroku(free plan) with ONE CLICK INSTALLATION BUTTON, then I found the free mysql offered by heroku was insufficient to use, its maxmum size is 5M, but wellcommerce will still take up 5.3M even after all products having been removed. Database size exceeds tier quota, write privileges is disabled, my attempt to change the admin's user name was in vain.
I tend to use mysql from other provider, of course, the database can be accessible remotely. After being deployed successfully, all its files are saved in slug, not in my repo, how can I get the codes and which file I should edit to change the connection strings?
Best regards,
Ethan

**Comment by adampiotrowski** [comment]
@educate All DB settings are stored in app/config/parameters.yml file.

**Comment by educate** [comment]
I don't understand why the size of database is over 5M after the deployment of sample site,  is it normal? You know, no image, no audio and video, only text, how come it takes 5M? I tried to optimize the database, but had no such privilege, now I'm planning to deploy to heroku manually, please tell me how to do in brief? Where I should make changes when comparing to  the installation method on your code page. Thank you!

**Comment by adampiotrowski** [comment]
@educate Yep, it's normal because of the count of the tables, indexes, data etc. Local DB requires also about 5M free size. AFAIK the only possible solutions for MySQL/MariaDB on Heroku are ClearDB and JawsDB but both with 5M (free plan). I changed the default fixtures_product_limit to 50 but with no success.

IMO manual install won't help because it changes nothing, you'll also use the same plan (free "ignite") on ClearDB.

At this moment I'll strongly recommend installing the app on localhost or using other provider. I'll check if we've any other capabilities to overcome this issue. You can also deploy the app to Heroku and then check if dropping unnecessary records (products, categories, producers) helps. Of course you can also change the ClearDB plan to something bigger. 

BTW. JawsDB was also a bad idea because they've an hourly queries limit of 3600 so it'll be exhausted every time during the install process.

**Comment by educate** [comment]
Thank you for your answer! Hope wellcommerce will be as popular as *agento soon.
