### ISSUE TITLE
Does wellcommerce work in php5?

### ISSUE THREAD

**Issue by RodolVelasco** [WellCommerce/WellCommerce#63]
Asking because I wanna try it but I have no experience at all working with php7

**Comment by adampiotrowski** [comment]
@RodolVelasco At this moment WellCommerce utilizes new PHP7 features such as return types. It won't run on lower PHP versions. We've bumped this requirement recently because PHP 5.6 will be supported for about 8 months from now and changing it in a hurry will cause too many BC breaks (see  [http://php.net/supported-versions.php](http://php.net/supported-versions.php))

If you own a VPS, the upgrade from 5.6 to 7 is pretty straightforward and in most cases shouldn't break anything (we've upgraded production servers for our legacy apps working on 5.6). You can also use one-click Deploy to Heroku button to set-up own demo. Heroku's free plan will be sufficient.
