### ISSUE TITLE
Order edit not working

### ISSUE THREAD

**Issue by folpy** [WellCommerce/WellCommerce#78]
Hi,

I found out another issue. When I try to open order in backoffice for editing there is 500 Internal Server Error. So I am not able to see order in backoffice.

Thanks for help.

**Comment by folpy** [comment]
Fatal error: Call to undefined method WellCommerce\Bundle\OrderBundle\Controller\Admin\OrderController::getOrderStorage()

**Comment by adampiotrowski** [comment]
@folpy Right :/. I've already pushed the fixes but if you're using composer there'll be no easy way to upgrade. You can either switch to Git (clone the repo) or wait till Friday, we'll be releasing next version, only fixes this time. 

Btw. using Git is highly recommended at this moment because of many changes & fixes we're pushing. Here's how to do it:

```
git clone git@github.com:WellCommerce/WellCommerce.git /path/to/wellcommerce
cd /path/to/wellcommerce
git checkout development
curl -s http://getcomposer.org/installer | php
php composer.phar update
php app/console wellcommerce:install
```
It will clone the repo, update the Composer packages, install DB schema, assets etc.

**Comment by folpy** [comment]
Thanks Adam for help :-) I think we can close this.
